
dialect  "mvel"

import com.lex.zhao.textKeyword.StrategyChoice.Latency;
import com.lex.zhao.textKeyword.StrategyChoice.BandWidth;
import com.lex.zhao.textKeyword.StrategyChoice.UtilizationRate
import com.lex.zhao.textKeyword.StrategyChoice
import com.lex.zhao.textKeyword.Scene_utilization;
import com.lex.zhao.textKeyword.networkconf.Server;
import com.lex.zhao.textKeyword.networkconf.Server.Port
import com.lex.zhao.textKeyword.Scene_utilization
import javafx.scene.Scene
import com.lex.zhao.textKeyword.BusinessIdentification.Scene_BusinessIdentification;

rule "low bandwidth"
    when
        BandWidth(value < 20)
    then
        System.out.println("老大，按你的要求，现在是Low Bandwidth策略");
end

rule "high bandwidth"
    when
        BandWidth(value >= 20)
    then
        System.out.println("老大，按你的要求，现在是High Bandwidth策略");
end

rule "utilizationRate"
    when
        $utilization : UtilizationRate()
    then
        System.out.println("The utilization rate is no more than "  + $utilization.getRate());
        Scene_utilization scene = new Scene_utilization($utilization.getRate());
        scene.run();
end

rule "serverConf"
    when
        $server : Server()
    then
        System.out.println($server);
        System.out.println($server.port.access ? "The port " + $server.port + " is accessed" : "The port " + $server.port + " is not accessed");
end


//rule "latency require"
//    when
//        Latency(latency < 10)
//    then
//        System.out.println("老大，按你的要求，现在是latency require策略");
//end
//
//rule "not latency require"
//    when
//        Latency(latency >= 10)
//    then
//        System.out.println("老大，按你的要求，现在是not latency require策略");
//end
